# Generated by Django 4.2 on 2023-05-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name of character', max_length=50, unique=True, verbose_name='Name')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Jméno',
                'verbose_name_plural': 'Jména',
                'ordering': ['name'],
            },
        ),
    ]
