# Generated by Django 4.2 on 2023-05-10 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gotapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name of place', max_length=50, unique=True, verbose_name='Name')),
                ('image', models.ImageField(help_text='Upload a image of place', upload_to='places', verbose_name='Image')),
                ('description', models.TextField(help_text='Enter a description of place', max_length=500, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name'], 'verbose_name': 'Character', 'verbose_name_plural': 'Characters'},
        ),
        migrations.AddField(
            model_name='character',
            name='actor',
            field=models.CharField(help_text='Enter a name of actor', max_length=80, null=True, verbose_name='Actor'),
        ),
        migrations.AddField(
            model_name='character',
            name='first_episode',
            field=models.CharField(help_text='Enter a first episode where character appears', max_length=50, null=True, verbose_name='First Episode'),
        ),
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(help_text='Upload a image of character', null=True, upload_to='characters', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name of house', max_length=50, unique=True, verbose_name='Name')),
                ('region', models.CharField(help_text='Enter a region of house', max_length=50, verbose_name='Region')),
                ('coat_of_arms', models.ImageField(help_text='Upload a coat of arms of house', null=True, upload_to='', verbose_name='Coat of Arms')),
                ('words', models.CharField(help_text='Enter a words of house', max_length=50, verbose_name='Words')),
                ('home', models.OneToOneField(help_text='Select a home of house', on_delete=django.db.models.deletion.CASCADE, to='gotapp.place', verbose_name='Home')),
            ],
            options={
                'verbose_name': 'House',
                'verbose_name_plural': 'Houses',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='character',
            name='house',
            field=models.ManyToManyField(help_text='Select a house of character', to='gotapp.house', verbose_name='House'),
        ),
    ]
